docker pull andrewmichaelsmith/docker-heartbleed
docker run -d andrewmichaelsmith/docker-heartbleed
docker ps #note conatiner id
docker inspect <container id> | grep IPAddress #note ip

how to run heartbleed
